### ISSUE TITLE
--format isn't applied to 480p/360p/240p/144p

### ISSUE THREAD

**Issue by po5** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#12]
As the height checks end at 720p, the video stream with the highest bitrate for 144p to 720p will be picked.
This could result in youtube-dl picking a lower resolution stream (assuming the highest bitrate stream for a given resolution can ever have a higher bitrate than the highest bitrate stream of a higher resolution, something I haven't been able to find on YouTube so far) and more importantly pick an unexpected codec.

Example video where the current format selection picks avc over av1: https://www.youtube.com/watch?v=tPEE9ZwTmy0

The fix would be to add cases for both >30fps and regular videos in the following resolutions: 144p, 240p, 360p, 480p

Alternatively, this will achieve the same results without hardcoding resolutions, and handle HDR streams better: `--format '(bestvideo[vcodec=vp9.2][fps>30]/bestvideo[vcodec^=av01][vcodec*=M.08.][fps>30]/bestvideo[vcodec^=vp9][fps>30]/bestvideo[vcodec^=av01][fps>30]/bestvideo[fps>30]/bestvideo[vcodec=vp9.2]/bestvideo[vcodec^=av01][vcodec*=M.08.]/bestvideo[vcodec^=vp9]/bestvideo[vcodec^=av01]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best[fps>30]/best'`

**Comment by TheFrenchGhosty** [comment]
I guess the format will need to be set to lower resolution.

>Alternatively, this will achieve the same results without hardcoding resolutions, and handle HDR streams better

Your fix is good, except that I actually want to hard-code the resolutions.

Also:

Is `bestvideo[vcodec^=av01][vcodec*=M.08.]` the thing to use to fix ["vp9 will destroy very fine detail because of all the optimizations, especially noticeable on low res videos where it look worse than avc."](https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/issues/9#issuecomment-645721048)?

**Comment by po5** [comment]
> Is `bestvideo[vcodec^=av01][vcodec*=M.08.]` the thing to use to fix ["vp9 will destroy very fine detail because of all the optimizations, especially noticeable on low res videos where it look worse than avc."](https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/issues/9#issuecomment-645721048)?

Not at all, this makes sure it picks SDR vp9 streams over HDR av1 (08 in `M.08.` refers to the bit-depth, 8 only lets SDR through) as YouTube's HDR av1 encodes are demonstrably worse.
See https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/issues/9#issuecomment-644355182

**Comment by TheFrenchGhosty** [comment]
>Not at all, this makes sure it picks SDR vp9 streams over HDR av1 (08 in M.08. refers to the bit-depth, 8 only lets SDR through) as YouTube's HDR av1 encodes are demonstrably worse.

Oh interesting, I will set it up later then.

>That new title is inaccurate as this affected 720p as well if we assume there can be lower resolution streams with higher bitrate.
It's whole reason for still hardcoding resolutions (at arbitrary YouTube-specific heights, without regard for other common resolutions like 576p).

If I'm correct, this should be fixed in https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/66a3d0de0b48bbd2835631e5ad8677ffee68cb86
