### ISSUE TITLE
Why is av01 chosen over vp9? 

### ISSUE THREAD

**Issue by happysmash27** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#21]
It appears [that vp9 has a better PSNR than av01](https://www.texpion.com/2018/07/av1-vs-vp9-vs-avc-h264-vs-hevc-h265-2-psnr.html), and in all the videos I have tested that have av01 at a high resolution, it appears that av01 also has a lower bitrate than vp9. So, wouldn't that mean that av01 is lower quality? Or am I missing something here?

**Comment by po5** [comment]
That article you linked shows that av1 at the same PSNR as vp9 produces more efficient videos.
I don't know where you got that "vp9 has a better PSNR than av01" because that's not what this says at all.

YouTube's SDR av1 encodes are clearly superior to their vp9 encodes, you can do your own comparisons on https://www.youtube.com/watch?v=CbUjuwhQPKs
The encode quality offered by YouTube for a given codec is why the codec selection does av1 > HDR vp9 > SDR vp9 > avc, what is *possible* to achieve with a given codec is irrelevant if YouTube doesn't take advantage of it.

Ideally we should avoid HDR av1 (see https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/issues/14)

**Comment by TheFrenchGhosty** [comment]
I think @po5 answered this question perfectly.

**Comment by lx30011** [comment]
Hi, sorry for reopening this issue.

I've downloaded this video: https://www.youtube.com/watch?v=aOq49euWnIo

The scripts pick format code 248
`248          webm       1920x1080  1080p 1260k , webm_dash container, vp9@1260k, 30fps, video only, 13.86MiB`

There is also format code 137
`137          mp4        1920x1080  1080p 2616k , mp4_dash container, avc1.640028@2616k, 30fps, video only, 28.78MiB`

I downloaded 137 for comparison and I must say, it looked a lot better. Especially in the beginning it's very clear that there is less compression going and and a lot more detail is visible.

Is this just an edge case?

**Comment by TheFrenchGhosty** [comment]
@lx30011 Yeah, I think so, the AVC of youtube is literally the worst video quality you can get, so it's either an edge case, or maybe the good encode is not yet ready (unlikely).

**Comment by mirh** [comment]
> YouTube's SDR av1 encodes are clearly superior to their vp9 encodes, you can do your own comparisons on https://www.youtube.com/watch?v=CbUjuwhQPKs

I don't really know why you chose such an incredibly peculiar video to make any test, it's mostly stylized graphics with some very low resolution archival footage here and there. 
It's so bad that you'd struggle to even find differences with H264 - there's absolutely no clear winner between AV1 and VP9. 

And I could telly you [here](https://www.youtube.com/watch?v=SElZABp5M3U) VP9 is actually the better one, quality-wise (even though this puny advantage comes at a 1.5x bigger size price)
