### ISSUE TITLE
[Windows] Windows being Windows / Powershell being dumb - Script not running

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#22]
I'm sorry if this is simple. I'm at a loss here. Been sitting here for the past few hours trying to get this to work.

https://i.imgur.com/E9RMhYZ.png

Added youtube-dl.exe and ffmpeg.exe to my path. Nothing.
cd'd into the directory with youtube-dl and the .ps1 file. Says youtube-dl is unrecognized.
I spent about 20 minutes trying to figure out how to even run the .ps1 file because Windows by default blocks all powershell scripts from running. Now I know to use "Set-ExecutionPolicy Bypass -Scope Process" immediately before running the script. This is not a permanent solution and needs to be run each and every time I want to run the script.

As a last ditch effort I tried running it in cli and it says the date format is unrecognized. 

https://i.imgur.com/vnq9Vry.png

Some clearer instructions would be appreciated so I can actually use the scripts you worked so hard to make! As well, how do you "install" youtube-dl and ffmpeg? They don't have windows installers. Just the .exe files. I'm assuming you mean to add them to path?

**Comment by TheFrenchGhosty** [comment]
I did test the windows version using Chocolatey to install both youtube-dl and ffmpeg. I didn't have any issue. However, this project is not made for Windows first, I don't use Windows for anything other than gaming, so my testing are minimal, if they run and download stuff: it's good enough for me.

>I spent about 20 minutes trying to figure out how to even run the .ps1 file because Windows by default blocks all powershell scripts from running.

I don't think that's true, I don't need to do anything to run them.

>As a last ditch effort I tried running it in cli and it says the date format is unrecognized.

Well yeah obviously, it's a Powershell function, reason why the script are .ps1 and not .bat.

>Some clearer instructions would be appreciated so I can actually use the scripts you worked so hard to make! As well, how do you "install" youtube-dl and ffmpeg? They don't have windows installers. Just the .exe files. I'm assuming you mean to add them to path?

I use Chocolatey, because this is how everyone should install software on Windows. It's working with it.

I will update the readme to recommend people to install youtube-dl/ffmpeg with it.

**Comment by TheFrenchGhosty** [comment]
Done:

https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/b22858403c4f8f3dcf7e3fe88614c403a93e5ddf

https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/96d052675d5622f5025e604b10bd95acddab07f9
